on:
  push:
    branches:
      - main

name: Release Packaging

jobs:
  release:
    name: Release Packaging
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Release Build
        run: cargo build --release --target=x86_64-pc-windows-msvc
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: gmcl_obj_parser_rs_win64
          path: target/x86_64-pc-windows-msvc/release/obj_parser_rs.dll
